export const memberData = [
  {
    id: 1,
    first_name: "Julian",
    last_name: "Wiley",
    full_name: "Julian Wiley",
    email: "julian@julianwiley.com",
    linkedIn: "https://www.linkedin.com/in/julian-wiley-8377b5175/",
    phone: "(225) 819-7690",
    website: "www.julianwiley.com",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "Oneye",
      website: "xhighlight.com",
    },
    media: {
      photo: "/download1.png",
      facebook: "https://www.facebook.com/",
    },
    about: "A paragraph about Julian",
  },
  {
    id: 2,
    first_name: "Alvie",
    last_name: "Stoddard",
    full_name: "Alvie Stoddard",
    email: "alviestoddard@gmail.com",
    linkedIn: "www.linkedin.com/in/alvst/",
    phone: "",
    website: "alvie.org",
    concentration:
      "Technology, Entrepreneurship, and Design, & Information Technology Management",
    working_on:
      "XHighlight - The fastest and easiest way to create your sports highlight videos.",
    introduction:
      "Alvie is an aspiring entrepreneur who is very interested in technology and programming. He is working on a startup, XHighlight, the fastest and easiest way to create sports and highlight videos. He is also CODE's most senior member, having lived in CODE since Sophomore year and being active in leadership decisions since the end of his freshman year.  Finally, he studied at Babson San Francisco in Spring 2018 and hopes to live out there upon graduation. Academics wise, he is a senior Graduating in May of 2021 and is concentrating in Technology, Entrepreneurship, and Design and Information Technology Management. ",
    year_of_graduation: "Senior Graduating Spring 2021",
    from: "Wellesley, MA",
    company: {
      name: "XHighlight",
      website: "xhighlight.com",
    },
    media: {
      photo: "/alvie.jpg",
    },
    about: "A paragraph about Alvie",
  },
  {
    id: 3,
    first_name: "Krishna",
    last_name: "Madala",
    full_name: "Krishna Madala",
    email: "kmadala1@babson.edu",
    linkedIn: "",
    phone: "",
    website: "",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "",
      website: "xhighlight.com",
    },
    media: {
      photo: "/stockPortrait2.jpg",
    },
    about: "A paragraph about ",
  },
  {
    id: 4,
    first_name: "Sumer",
    last_name: "Sen",
    full_name: "Sumer Sen",
    email: "ssen2@babson.edu",
    linkedIn: "",
    phone: "",
    website: "",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "",
      website: "xhighlight.com",
    },
    media: {
      photo: "/stockPortrait3.jpg",
    },
    about: "A paragraph about ",
  },
  {
    id: 5,
    first_name: "Amay",
    last_name: "Maheshwari",
    full_name: "Amay Maheshwari",
    email: "amaheshwari2@babson.edu",
    linkedIn: "",
    phone: "",
    website: "",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "",
      website: "xhighlight.com",
    },
    about: "A paragraph about ",

    media: {
      photo: "/stockPortrait4.jpg",
    },
  },
  {
    id: 6,
    first_name: "Thomas",
    last_name: "Croissant",
    full_name: "Thomas Croissant",
    email: "tcroissant1@babson.edu",
    linkedIn: "",
    phone: "",
    website: "",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "",
      website: "xhighlight.com",
    },
    media: {
      photo: "/stockPortrait5.jpg",
    },
    about: "A paragraph about ",
  },
  {
    id: 7,
    first_name: "Angel",
    last_name: "Hill",
    full_name: "Angel Hill",
    email: "ahill3@babson.edu",
    linkedIn: "",
    phone: "",
    website: "",
    concentration: "",
    working_on: "",
    introduction: "",
    year_of_graduation: "",
    from: "",
    company: {
      name: "",
      website: "xhighlight.com",
    },
    media: {
      photo: "/stockPortrait6.jpg",
    },
    about: "A paragraph about ",
  },
];
